In [2]:
import numpy as np
new_array=np.array([1,2,3,4,5,6,7,8,9])
num_list=new_array .tolist()
print("The list is", new_array)


The list is [1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
a = np.arange(9).reshape(3,3)
result = np.trace(a)
print("The sum of the diagonal elements", result)

The sum of the diagonal elements 12


In [14]:
import numpy as np
x = np.array([[1,2],[3,5]])
print("the values higher than",x[x>=3] )


the values higher than [3 5]


In [16]:
import numpy as np
a = np.array([[2,4],[6,8]])
b = np.array([[10,12],[14,16]])
c = np.add(a,b)
print(c)


[[12 16]
 [20 24]]


In [17]:
import numpy as np
a = np.random.rand(3,4)
b = a-a.mean(axis=1, keepdims=True)
print(b)


[[ 0.0374537   0.28601688 -0.17337717 -0.15009341]
 [-0.18667971 -0.364422    0.2962274   0.25487432]
 [ 0.13552942 -0.38751625  0.29023431 -0.03824748]]
