In [2]:
import numpy as np
new_array=np.array([1,2,3,4,5,6,7,8,9])
num_list=new_array .tolist()
print("The list is", new_array)


The list is [1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
a = np.arange(9).reshape(3,3)
result = np.trace(a)
print("The sum of the diagonal elements", result)

The sum of the diagonal elements 12


In [14]:
import numpy as np
x = np.array([[1,2],[3,5]])
print("the values higher than",x[x>=3] )


the values higher than [3 5]


In [24]:
import numpy as np
a = np.array([[2,4],[6,8]])
b = np.array([[10,12],[14,16]])
c = np.add(a,b)
print(c)


[[12 16]
 [20 24]]


In [25]:
import numpy as np
a = np.random.rand(3,4)
b = a-a.mean(axis=1, keepdims=True)
print(b)


[[ 0.49825115 -0.36393338  0.1753709  -0.30968867]
 [ 0.24046362 -0.25288661  0.09690292 -0.08447993]
 [-0.03624886 -0.05142115  0.09139475 -0.00372474]]
